import { useEffect, useState } from 'react'
import './App.css'

type Card = { id: number; title: string; description: string; category: string; art: string; saved: boolean }
const initialCards: Card[] = [
  { id: 1, title: 'A little room to breathe', description: 'Slow down, find your balance, and make a little space for yourself.', category: 'Wellbeing', art: 'balance', saved: false },
  { id: 2, title: 'Small steps, big things', description: 'Every good idea starts somewhere. Give yours a place to grow.', category: 'Personal growth', art: 'steps', saved: true },
  { id: 3, title: 'Find your flow', description: 'Less distraction. More intention. Make time for what matters.', category: 'Productivity', art: 'flow', saved: false },
  { id: 4, title: 'Make something just because', description: 'Follow your curiosity and see where a little creativity takes you.', category: 'Creativity', art: 'create', saved: false },
  { id: 5, title: 'Good things take time', description: 'You don’t have to have it all figured out. Keep growing at your pace.', category: 'Personal growth', art: 'grow', saved: false },
  { id: 6, title: 'The joy of doing less', description: 'A gentle reminder that a full life doesn’t need a full calendar.', category: 'Wellbeing', art: 'sunset', saved: false },
]
const categories = ['All cards', 'Wellbeing', 'Personal growth', 'Productivity', 'Creativity']
function Bookmark({ filled = false }: { filled?: boolean }) { return <svg width="17" height="19" viewBox="0 0 20 22" fill={filled ? 'currentColor' : 'none'} aria-hidden="true"><path d="M5 3h10a1 1 0 0 1 1 1v15l-6-4-6 4V4a1 1 0 0 1 1-1Z" stroke="currentColor" strokeWidth="1.4" strokeLinejoin="round" /></svg> }
function App() {
  const [cards, setCards] = useState<Card[]>(() => { try { const value = JSON.parse(localStorage.getItem('simple-cards') || 'null'); return Array.isArray(value) && value.every(card => typeof card.title === 'string' && typeof card.description === 'string') ? value : initialCards } catch { return initialCards } })
  const [category, setCategory] = useState('All cards')
  const [savedOnly, setSavedOnly] = useState(false)
  const [search, setSearch] = useState('')
  const [adding, setAdding] = useState(false)
  const [selected, setSelected] = useState<Card | null>(null)
  useEffect(() => { localStorage.setItem('simple-cards', JSON.stringify(cards)) }, [cards])
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { setAdding(false); setSelected(null) } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [])
  const visible = cards.filter(card => (!savedOnly || card.saved) && (category === 'All cards' || category === card.category) && `${card.title} ${card.description}`.toLowerCase().includes(search.toLowerCase()))
  const toggleSave = (id: number) => setCards(cards.map(card => card.id === id ? { ...card, saved: !card.saved } : card))
  function addCard(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    const title = String(data.get('title')).trim(); const description = String(data.get('description')).trim()
    if (!title || !description) return
    setCards([...cards, { id: Date.now(), title, description, category: String(data.get('category')), art: 'balance', saved: false }]); setAdding(false); setCategory('All cards'); setSavedOnly(false); setSearch('')
  }
  return <div className="app-shell">
    <header><a className="brand" href="#" aria-label="Simple home"><span>✳</span> simple<span className="brand-dot">.</span></a><nav aria-label="Main navigation"><button className={!savedOnly ? 'active' : ''} onClick={() => setSavedOnly(false)}>Discover</button><button className={savedOnly ? 'active' : ''} onClick={() => setSavedOnly(true)}>Saved cards <span className="nav-count">{cards.filter(card => card.saved).length}</span></button></nav><div className="avatar" aria-label="Your workspace">S</div></header>
    <main><section className="intro"><div className="eyebrow"><span /> A LITTLE INSPIRATION FOR YOUR EVERYDAY</div><div className="intro-row"><div><h1>Good things, <em>one card at a time.</em></h1><p>A collection of ideas to help you slow down, get inspired, and keep growing.</p></div><button className="primary" onClick={() => setAdding(true)}><span>+</span> Create a card</button></div></section>
    <section className="collection" aria-label="Card collection"><div className="toolbar"><div className="filters" aria-label="Filter by category">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={category === item ? 'selected' : ''} aria-pressed={category === item}>{item}</button>)}</div><label className="search"><svg width="16" height="16" viewBox="0 0 20 20" fill="none" aria-hidden="true"><circle cx="8.5" cy="8.5" r="5.5" stroke="currentColor" strokeWidth="1.5"/><path d="m13 13 4 4" stroke="currentColor" strokeWidth="1.5"/></svg><input aria-label="Search cards" placeholder="Search cards..." value={search} onChange={event => setSearch(event.target.value)} /></label></div><div className="collection-info"><span>{savedOnly ? 'Your saved inspiration' : category === 'All cards' ? 'A little something for every part of you' : category}</span><span>{visible.length} cards</span></div>
    <div className="card-grid">{visible.map(card => <article className="card" key={card.id}><div className={`card-art ${card.art}`}><div className="art-shape shape-one"/><div className="art-shape shape-two"/><div className="art-shape shape-three"/><div className="art-shape shape-four"/><span className="art-spark">✧</span><button className={`save ${card.saved ? 'is-saved' : ''}`} aria-label={`${card.saved ? 'Unsave' : 'Save'} ${card.title}`} aria-pressed={card.saved} onClick={() => toggleSave(card.id)}><Bookmark filled={card.saved}/></button><span className="art-caption">{({ balance: 'take a breath', steps: 'one step at a time', flow: 'less, but better', create: 'stay curious', grow: 'trust the process', sunset: 'simply be' } as Record<string, string>)[card.art]}</span></div><div className="card-content"><span className={`category ${card.category.toLowerCase().replace(' ', '-')}`}>{card.category}</span><h2><button onClick={() => setSelected(card)}>{card.title}</button></h2><p>{card.description}</p><div className="card-bottom"><span><span className="tiny-flower">✳</span> A little perspective</span><button onClick={() => setSelected(card)} aria-label={`Open ${card.title}`}>↗</button></div></div></article>)}</div>
    {!visible.length && <div className="empty"><span>✧</span><h2>A little space for something good.</h2><p>{savedOnly ? 'Save a card to keep your inspiration close.' : 'Try another search or create a card of your own.'}</p><button onClick={() => { setSearch(''); setCategory('All cards'); setSavedOnly(false) }}>Explore all cards ↗</button></div>}
    </section><div className="closing"><span>✳</span><p>You don’t have to do it all. Just start with what speaks to you.</p></div></main><footer><span><strong>simple.</strong> A little less noise. A little more you.</span><span>Made for a more intentional everyday <span className="footer-flower">✳</span></span></footer>
    {(adding || selected) && <div className="modal-backdrop" onClick={() => { setAdding(false); setSelected(null) }}><dialog open className="modal" aria-label={adding ? 'Create a card' : selected?.title} onClick={event => event.stopPropagation()}><button className="modal-close" autoFocus={!adding} onClick={() => { setAdding(false); setSelected(null) }} aria-label="Close">×</button>{adding ? <form onSubmit={addCard}><span className="eyebrow">MAKE ROOM FOR AN IDEA</span><h2>Create a little inspiration.</h2><label>Title<input name="title" autoFocus required maxLength={65} placeholder="What’s on your mind?"/></label><label>Description<textarea name="description" required maxLength={220} placeholder="A thought worth keeping..."/></label><label>Category<select name="category">{categories.slice(1).map(item => <option key={item}>{item}</option>)}</select></label><button className="primary" type="submit">Create card ↗</button></form> : selected && <><span className="category">{selected.category}</span><h2>{selected.title}</h2><p>{selected.description}</p><div className="reflection"><span className="eyebrow">A MOMENT TO REFLECT</span><p>What’s one small way you can bring this idea into your day?</p></div><button className="primary" onClick={() => toggleSave(selected.id)}><Bookmark filled={cards.find(card => card.id === selected.id)?.saved}/>{cards.find(card => card.id === selected.id)?.saved ? 'Saved to your collection' : 'Save this card'}</button></>}</dialog></div>}
  </div>
}
export default App
